### ISSUE TITLE
grpcfd produces memory leaks

### ISSUE THREAD

**Issue by denis-tingaikin** [edwarnicke/grpcfd#25]
## Motivation

During using the grpcfd, we found goroutine leaks that could produce memory leaks in involved applications.

![image](https://github.com/edwarnicke/grpcfd/assets/49399980/db6751f8-f467-4b44-bbb5-e435f53ce885)

## Soltuion

1. Add tests. Repository doesn't have tests that is looking critical.
2. Change intrerfaces

https://github.com/edwarnicke/grpcfd/blob/main/connwrap.go#L44-L56

```go
type FDSender interface {
	SendFD(fd uintptr) <-chan error
	SendFile(file SyscallConn) <-chan error
	SendFilename(filename string) <-chan error
}

type FDRecver interface {
	RecvFD(dev, inode uint64) <-chan uintptr
	RecvFile(dev, ino uint64) <-chan *os.File
	RecvFileByURL(urlStr string) (<-chan *os.File, error)
	RecvFDByURL(urlStr string) (<-chan uintptr, error)
}
```

The provided elements could produce memory leaks because they don't use context for canceling operations.

Suggested to change it to

```go
type FDSender interface {
	SendFD(ctx context.Context, fd uintptr) <-chan error
	SendFile(ctx context.Context, file SyscallConn) <-chan error
	SendFilename(ctx context.Context, filename string) <-chan error
}

type FDRecver interface {
	RecvFD(ctx context.Context, dev, inode uint64) <-chan uintptr
	RecvFile(ctx context.Context, dev, ino uint64) <-chan *os.File
	RecvFileByURL(ctx context.Context, urlStr string) (<-chan *os.File, error)
	RecvFDByURL(ctx context.Context, urlStr string) (<-chan uintptr, error)
}
```

The using of context can prevent edge cases for grpcfd.

Related to https://github.com/networkservicemesh/cmd-nsmgr/issues/675

**Comment by denis-tingaikin** [comment]
Profile: [goroutinelimit1.zip](https://github.com/edwarnicke/grpcfd/files/15254489/goroutinelimit1.zip)

**Comment by edwarnicke** [comment]
Some things to keep in mind wrt resource management in grpcfd:

1.   We have three go routines: 
  1. [One in RecvFile](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L270-L279) - which loops until the ```<-chan uintptr``` returned from [RecvFD](https://github.com/edwarnicke/grpcfd/blob/main/connwrap.go#L231) is closed
  2. [One in SendFile](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L205-L210) that loops until the ```<-chan error``` returned by [SendFD](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L172) is closed.
  3. [One in SendFilename](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap_linux.go#L35-L44) that loops until the ```<-chan error``` returned by [SendFile](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L189) is closed.

## Go Routine in RecvFile

[The go routine in RecvFile](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L270-L279) -loops until the ```<-chan uintptr``` returned from [RecvFD](https://github.com/edwarnicke/grpcfd/blob/main/connwrap.go#L231) is closed.  

[RecvFD creates the fdCh it returns](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L232).  In [connWrap.recvExecutor.AsyncExec](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L233) either we have an fd already for the requested (dev,ino), in which case we see the [fdCh closed](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L251) or we don't, in which case we [store fdCh in connWrap.recvFDChans](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L255C32-L255C44).

This leaves us with two questions:

1. When is the [fdCh stored connWrap.recvFDChans](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L255C32-L255C44) closed?
2.  Could AsyncExec be deadlocking?
### When is the [fdCh stored connWrap.recvFDChans](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L255C32-L255C44) closed?

In [connWrap.Read](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L291) if a read results in us [receiving an fd](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L330) we [iterate through the connWrap.recvFDChans](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L333-L342) to see if there's a fdCh waiting to receive it.  If so we [send it and close the fdCh](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L340-L341).  So if we receive an fd for the (dev,ino) after its been asked for, the fdCh should be closed, and the corresponding go routine(s) should exit and not leak.

If the [connWrap as a net.Conn is Closed](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L114-L119) or [garbage collected](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L96-L98) we call [connWrap.close](https://github.com/edwarnicke/grpcfd/blob/main/connwrap.go#L107) and [loop through connWrap.recvFDchans closing all the fdChs](https://github.com/edwarnicke/grpcfd/blob/c8612f7f2b168974e69d52f8b11bb6fadfd302cb/connwrap.go#L114-L119) which would cause all corresponding go routines to exit.

Net-net: all go routines should exit after the connWrap as a net.Conn is Closed or garbage collected unless AsyncExec is deadlocking, or something really strange is happening.  Expectations should therefore be that no go routine is leaked past the Close or garbage collection point.

**Comment by denis-tingaikin** [comment]
New incident reported by Szilard:

[nsmgr_goroutineprofiles_20240519215928.tar.gz](https://github.com/edwarnicke/grpcfd/files/15370918/nsmgr_goroutineprofiles_20240519215928.tar.gz)

**Comment by denis-tingaikin** [comment]
![image](https://github.com/edwarnicke/grpcfd/assets/49399980/e72b6f48-b74f-421d-9cfb-7310a6ea83bf)

**Comment by denis-tingaikin** [comment]
@edwarnicke 

I've found a suspect place, pelase have a look 

1. here creates a errCh  with size 1 https://github.com/edwarnicke/grpcfd/blob/cd38d280dac6d6809c87bcaca517fb134e54b215/connwrap.go#L191
2. here it creates a goroutine that can write in the errCh https://github.com/edwarnicke/grpcfd/blob/cd38d280dac6d6809c87bcaca517fb134e54b215/connwrap.go#L206
3. and if we got error from https://github.com/edwarnicke/grpcfd/blob/cd38d280dac6d6809c87bcaca517fb134e54b215/connwrap.go#L198
then we can get a leak

**Comment by denis-tingaikin** [comment]
>  I think upping the buffers to 50 is likely overkill... 

Totally agree. Currently, it's needed for testing. We can quickly use this solution only for patch release (v1.13.1), but we first need to get results.

**Comment by denis-tingaikin** [comment]
> Good catch. I think upping the buffers to 50 is likely overkill. 

Hmm, I can also be wrong because, in this case, we should panic about sending on the closed channel. So, most likely, it can be deadlocks in executors or cached connections that are not closed, as you mentioned above.
